const products = [
  {
    id: 1,
    name: "Product A",
    description: "Description of Product A",
    price: 9.99,
    image: "assets/shop/h_product01.jpg",
    category: "Electronics",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 2,
    name: "Product B",
    description: "Description of Product B",
    price: 19.99,
    image: "assets/shop/h_product02.jpg",
    category: "Clothing",
    rating: 3.8,
    reviews: 25,
  },
  {
    id: 3,
    name: "Product C",
    description: "Description of Product C",
    price: 14.99,
    image: "assets/shop/h_product03.jpg",
    category: "Home & Kitchen",
    rating: 4.2,
    reviews: 75,
  },
  {
    id: 4,
    name: "Product D",
    description: "Description of Product D",
    price: 29.99,
    image: "assets/shop/h_product04.jpg",
    category: "Sports & Outdoors",
    rating: 4.8,
    reviews: 100,
  },
  {
    id: 5,
    name: "Product E",
    description: "Description of Product E",
    price: 7.99,
    image: "assets/shop/h_product05.jpg",
    category: "Beauty & Personal Care",
    rating: 4.1,
    reviews: 30,
  },
  {
    id: 6,
    name: "Product F",
    description: "Description of Product F",
    price: 24.99,
    image: "assets/shop/h_product06.jpg",
    category: "Toys & Games",
    rating: 4.4,
    reviews: 60,
  },
];

export default products;
